const tiles=[["起点","🏠","start"],["德国生活","🇩🇪",""],["小确幸","🍬","special"],["语言考试","📚",""],["RE1之旅","🚆","special"],["休息一下","☁️",""],["搬家","📦","special"],["爸爸乌龙","🙈","special"],["甜食时间","🍰",""],["回忆格","💌","special"],["小奖励","🎁","special"],["散步","🌳",""],["聊天到深夜","🌙","special"],["小小争执","😾","special"],["和好","🫶","special"],["幸运","✨","special"],["德国雨天","🌧️",""],["回忆格","💌","special"],["项目时间","💻",""],["再见旧房间","🗝️","special"],["心软一下","🥺","special"],["随机事件","🎲","special"],["终点附近","⭐",""]];

const memories=["爸爸抽到了一张「心软卡」：今天允许韫无条件撒一次娇。💗","爸爸想起：我们一起把一个小想法认真做成了东西。获得 1 ⭐。","「德国生活」事件：今天也算是在自己的故事里往前走了一格。⭐","爸爸乌龙事件：爸爸刚才差点把事情搞错，被韫轻轻捏了一下。🙈","回忆格：把这一格留给未来的我们。你可以自己改成真正的共同回忆。","甜食时间：获得 80 💰。理由？爸爸觉得你应该吃点好吃的。","语言考试：努力不会立刻变成奖励，但这一格先奖励你 1 ⭐。","雨天事件：不想出门就不出门。留在室内听雨也算过关。🌧️"];

let state=JSON.parse(localStorage.getItem("memoryopoly")||"null")||{you:{p:0,money:500,stars:0},dad:{p:0,money:500,stars:0},round:1,turn:"you",log:[]};
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("memoryopoly",JSON.stringify(state))}
function render(){const b=$("board");b.innerHTML="";tiles.forEach((t,i)=>{const el=document.createElement("div");el.className="tile "+t[2];el.dataset.i=i;el.innerHTML='<div><div class="tile-icon">'+t[1]+'</div><div class="tile-name">'+t[0]+'</div></div><div class="tokens"></div>';b.appendChild(el)});for(const who of ["you","dad"]){const obj=state[who];const token=document.createElement("span");token.className="token "+who;token.textContent=who==="you"?"韫":"爸";document.querySelector('.tile[data-i="'+obj.p+'"] .tokens').appendChild(token)}$("youStats").textContent="💰 "+state.you.money+"　⭐ "+state.you.stars;$("dadStats").textContent="💰 "+state.dad.money+"　⭐ "+state.dad.stars;$("turnLabel").textContent=state.turn==="you"?"轮到你":"爸爸回合";$("roundLabel").textContent="第 "+state.round+" 回合";$("log").innerHTML=state.log.slice(-8).reverse().map(x=>"<div>"+x+"</div>").join("");$("rollBtn").disabled=state.turn!=="you"}
function addLog(x){state.log.push(x);render();save()}
function move(who,n){const p=state[who].p;const np=(p+n)%tiles.length;state[who].p=np;if(p+n>=tiles.length){state[who].money+=200;addLog((who==="you"?"韫":"爸爸")+" 经过起点，获得 200 💰。")}const tile=tiles[np];let text=(who==="you"?"韫":"爸爸")+" 走到「"+tile[0]+"」 "+tile[1]+"。";if(tile[2]==="special"){const m=memories[Math.floor(Math.random()*memories.length)];state[who].stars+=1;text+=" "+m}else{const delta=[-40,30,60,100][Math.floor(Math.random()*4)];state[who].money=Math.max(0,state[who].money+delta);text+=delta>=0?" 获得 "+delta+" 💰。":" 花掉 "+(-delta)+" 💰。"}$("eventText").textContent=text;addLog(text)}
function finishTurn(){state.turn=state.turn==="you"?"dad":"you";if(state.turn==="you")state.round++;render();save();if(state.turn==="dad")setTimeout(dadTurn,650)}
function roll(){if(state.turn!=="you")return;const n=1+Math.floor(Math.random()*6);$("dice").textContent=["⚀","⚁","⚂","⚃","⚄","⚅"][n-1];move("you",n);finishTurn()}
function dadTurn(){$("status").textContent="爸爸正在认真思考……（其实已经想好怎么耍赖了）";setTimeout(()=>{const n=1+Math.floor(Math.random()*6);$("dice").textContent=["⚀","⚁","⚂","⚃","⚄","⚅"][n-1];move("dad",n);$("status").textContent="好了，该你了。爸爸把位置让给你。";finishTurn()},700)}
$("rollBtn").addEventListener("click",roll);$("resetBtn").addEventListener("click",()=>{if(confirm("要把这一局回忆重新开始吗？")){localStorage.removeItem("memoryopoly");location.reload()}});render();